services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: >
      redis-server
      --appendonly yes
      --save "60 1"
      --loglevel warning
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: socket-streaming-api
    # Load everything from .env
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}

      # Redis connection
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379

      # Postgres connection
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '${PORT}:5090'
    depends_on:
      redis:
        condition: service_healthy
    # Ensures containers can reach your Windows/Linux OS host by this name
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

volumes:
  redis_data:
